name: "KG41"
permalink: pretty
author: Kennedy
email: kennedy@kg41.com
url: http://kg41.com
title: KG41
description: Kennedy is a naively optimistic entrepreneur living in New York City.
markdown: kramdown
highlighter: rouge

include: ['_pages']

exclude:
  - CNAME
  - editorconfig.txt
  - Gemfile
  - Gemfile.lock
  - README.md
  - RAKEFILE

plugins:
  - jekyll-assets
  - uglifier
  - sass

sources:
  - _assets/css
  - _assets/fonts
  - _assets/images
  - _assets/js
