name: "Kennedy's Garage"
permalink: pretty
author: Kennedy
email: kennedysgarage@gmail.com
url: http://kennedysgarage.com
title: Kennedy's Garage
description: Kennedy is a naively optimistic entrepreneur living in New York City.
markdown: kramdown
highlighter: rouge

include: ['_pages']

exclude:
  - CNAME
  - editorconfig.txt
  - Gemfile
  - Gemfile.lock
  - README.md
  - RAKEFILE

plugins:
  - jekyll-assets
  - uglifier
  - sass

sources:
  - _assets/css
  - _assets/fonts
  - _assets/images
  - _assets/js

navigation:
- text: About
  url: /about/
- text: Projects
  url: /projects/
- text: Articles
  url: /articles/
