name: "KG41"
permalink: pretty
author: Kennedy
email: kennedysgarage@gmail.com
url: http://kennedysgarage.com
title: KG41
description: Portfolio of Kennedys Garage
markdown: kramdown
highlighter: rouge

include: ['_pages']

exclude:
  - CNAME
  - editorconfig.txt
  - Gemfile
  - Gemfile.lock
  - README.md
  - RAKEFILE

plugins:
  - jekyll-assets
  - uglifier
  - sass

sources:
  - _assets/css
  - _assets/fonts
  - _assets/images
  - _assets/js
