<?php  $title = 'Tom Green Site Redesign |'; include '../header.php'; ?>

<article>

<h2>Tom Green Site Redesign</h2>

<p>I have been a huge fan of Tom Green for as long as I can remember. I used to watch The Tom Green Show religiously and still enjoy his movies today. A few years ago I discovered that he is still producing content on his website <a href="http://www.tomgreen.com/">tomgreen.com</a>, and I have been keeping up as an active watcher. Recently I had the opportunity to meet Tom Green at <a href="http://www.comixny.com/">Comixs</a> when he was on tour. I have meet a lot of celebrities and famous people before, but never had I been this excited. Durning his show he even threw my wife his guitar pick. It was great watching him interact with the other fans; you can tell that he truly cares about all of them. That day will go down in my history book at the top 10 moments in my life.</p>
<p><img src="/articles/assets/tom-green-site-redesign/tomgreenandme.jpg"/></p>
<p>With Tom Green on tour I have a feeling that a lot of old fans are reconnecting with him. I am sure that his site is growing in numbers and strong. I have decided to come up with my own design of his site to keep up with the times and the growing numbers. The current design is a bit clustered, but yet it gets to the point of his site...videos. What would Tom Green be without his videos? But I think after that the site starts to get lost in itself. There are a number of site components he his trying getting across: Newsletter, Tour, Skype Team, Twitter, a poll, and other randomness that doesn't come across very clear.</p>
<p>Here is my rendition of what I think the site should look like. You can see that we still focus on the videos as the main feature. The second thing that seems important to Tom is his blog. The other thing I think he should focus on is his membership followed up with his sponsors. The video is the main focus with three other videos to select from. I have only chose three videos to give fans a taste of the past shows. The main video spot would be the last video shot or the video that is currently live. The other three spots would be the most popular videos from different categories. For example, one spot could be the most popular video from the The Tom Green Show to give old fans a way to reconnect with him- watching him in a familiar setting. Then we move down to his blog and what he has to tell the world. There is not much to do here except to clean it up a little. Currently on his site he has a lot of promotions but they seem to be a bit scattered. He also has Google AdSense gaining a little money I'm sure. I think the main focus of all of these promotions should be his membership. The membership would offer to him a higher chance of return visitors and a nice increasing, steady income a month. I would suggest getting rid of Google AdSense and focus on selling ad spots. I am sure that he would make a lot more money that way. He could also use his own promotions in this area. The last part is the footer. I am not 100% satisfied with this part yet. Moving from left to right we start off with the basic information that users need to know for Tom Green and his website, then we remind people of his shows and all the different categories for them, and lastly we give the users a way to stay further in connect with him and stay updated with all the current events by signing up for his newsletter.</p>
<p><img src="/articles/assets/tom-green-site-redesign/tg02.png"/></p>
<p>If you are a Tom Green Fan or just a reader of this post please let me know what you think. If this is Tom Green or a staff member, please feel free to <a href="mailto:kennedysgarage@gmail.com">contact me</a>.</p>

<p class="byline">August 1st, 2011 &there4; Kennedy</p>

</article>

<?php include("../footer.php"); ?>
